# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]:-${(%):-%x}}")")"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by init-submodules-no-riscv-tools.sh
__DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]:-${(%):-%x}}")")"
PATH=$__DIR/bin:$PATH
PATH=$__DIR/software/firemarshal:$PATH
# line auto-generated by build-toolchains.sh
<<<<<<< HEAD
source /home/tiago.almeida/gemmini.cluster/env-esp-tools.sh
=======
source /home/tiago/chipyard/env-esp-tools.sh
>>>>>>> facc0a5c41f4898a30d456cb6acd37a012a8edee
